### ISSUE TITLE
linux服务通过docker安装服务端如何添加服务的音乐

### ISSUE THREAD

**Issue by Lishuhao-lucky** [orangex/LazzyMusic#3]
服务端是linux通过docker运行的，通过端口在web端可以登陆，但无法添加音乐等操作；
手机端注册并登陆后无法看到音乐，音乐文件已在服务器上通过docker的文件映射了

**Comment by orangex** [comment]
> 服务端是linux通过docker运行的，通过端口在web端可以登陆，但无法添加音乐等操作； 手机端注册并登陆后无法看到音乐，音乐文件已在服务器上通过docker的文件映射了

你在手机浏览器可以正常访问 192.168.112.2:23333  吗？登录后，app 设置里尝试手动触发扫描入库试试。 因为  docker 版没有UI 不像桌面端可以通过托盘菜单触发扫描入库。
